In [20]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [28]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00000000
CPU times: total: 0 ns
Wall time: 0 ns


In [30]:
%%time
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.03058100
0.13819909
CPU times: total: 1.81 s
Wall time: 2.13 s


In [32]:
# embeddings, torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all the examples of functions/methods with pytorch docs)

# Define a prob tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each prob points to the index of the probabilirt in the tensor
# Draw 5 samples from  the multinimal distrubution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [34]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [35]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [36]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [37]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [38]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [40]:
input = torch.zeros(2,3,4)
out1 = input.transpose(0,1)
out2 = input.transpose(-2,-1)
print(out1.shape)
print(out2.shape)
# torch.permute works the same but you provide the new order of dimensions instead of the dimensions you'd like to swap.


torch.Size([3, 2, 4])
torch.Size([2, 4, 3])


In [42]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tenosrs along a new dimesion
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [43]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-1.9242, -1.1971, -4.3156], grad_fn=<SqueezeBackward4>)


In [44]:
import torch.nn.functional as F

# Crete a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# apply
softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [47]:
# init an embed layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# create some input indices
input_indices = torch.LongTensor([1, 5,  3, 2])

#apply the embedding layer
embedded_output = embedding(input_indices)

#the output will be a tensor of shape (4, 100), whjeree 4 is the number of inputs
# and 100 is the dimensionalirt of the eembedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[-0.3552,  0.9902,  0.6563, -0.1320, -0.8413, -0.0394],
        [ 1.0517, -0.6778, -2.0950,  1.1949,  0.0831,  0.5955],
        [ 0.6632,  0.6559,  1.2674, -0.7755,  0.9321,  1.9854],
        [-0.6797,  1.3721, -0.1568,  1.4068, -1.8555,  0.0472]],
       grad_fn=<EmbeddingBackward0>)


In [50]:
a = torch.tensor([[1,2], [3,4], [5,6]])
b = torch.tensor([[7,8,9], [10,11,12]])
print(a @ b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [53]:
int_64 = torch.randint(1, (3,2)).float()
#type int64
float_32 = torch.rand(2,3)
#type float32
print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

torch.float32 torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [56]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x, y, z)
print(x,y,z)
print(a.shape)

torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])


In [57]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
#print(input)
print(output[:, -1, :])

tensor([[6.4993e-01, 3.3401e-01, 6.2100e-01, 7.1328e-01, 1.3454e-02, 2.9118e-01,
         5.8331e-01, 5.8340e-02, 7.4311e-02, 1.8450e-02],
        [7.2969e-01, 7.6815e-01, 9.1126e-01, 3.0175e-01, 4.7051e-01, 3.6621e-01,
         1.4163e-01, 3.7287e-01, 7.5687e-01, 6.4917e-01],
        [2.0406e-01, 1.3176e-01, 1.2037e-01, 8.0063e-01, 4.1848e-01, 3.3595e-02,
         6.8039e-01, 2.4119e-01, 3.4890e-01, 1.5099e-01],
        [7.8998e-01, 9.0605e-01, 9.9355e-01, 8.6856e-01, 2.9495e-01, 8.5102e-01,
         2.9418e-02, 3.0125e-01, 3.9594e-02, 3.9986e-01],
        [8.4958e-01, 5.3966e-04, 2.0335e-03, 6.0770e-01, 1.5452e-01, 7.1239e-01,
         7.2098e-01, 2.8092e-01, 6.9865e-01, 8.3431e-01],
        [2.2373e-01, 6.7202e-01, 3.3628e-01, 8.8274e-01, 6.6550e-01, 8.1562e-01,
         1.0132e-01, 7.9682e-01, 3.7377e-01, 2.2290e-01],
        [2.6713e-01, 8.2764e-01, 3.1438e-01, 1.8374e-01, 8.8496e-01, 2.1670e-01,
         4.6850e-01, 8.1411e-01, 8.2223e-01, 6.4684e-01],
        [3.4251e-01, 4.8484

IndexError: too many indices for tensor of dimension 2

In [59]:
x = torch.tensor([10], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([1.])
